# Generated by Django 3.1.1 on 2020-12-22 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20201216_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='endTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 29, 16, 19, 35, 415215)),
        ),
    ]
